### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by PersonaA** [betterobjects/activeql#2]
Is there a way to throw common error if permission (from entity configuration) denied?

**Comment by thorek** [comment]
When using configuration an error is only thrown when the client makes an „impossible“ request (query by ID). In all other cases the data are simply limited because the client should have no knowledge about the permission restrictions.  

But you can always use a callback function instead and handle exceptions in any way you want. 

If you think the permission configuration should add another way of handling unallowed requests, feel free to add a feature request.
